### ISSUE TITLE
If I share the generated report it is not displaying correctly.. ?

### ISSUE THREAD

**Issue by changan1111** [ortoniKC/ortoni-report#11]
If I share the generated report .. it is not working in a standalone report., if they have the project and they drop in the project folder, they are able to view the report properly.. But person who does not have project, it is not displaying correctly

**Comment by ortoniKC** [comment]
> If I share the generated report .. it is not working in a standalone report., if they have the project and they drop in the project folder, they are able to view the report properly.. But person who does not have project, it is not displaying correctly

Yes, as the HTML file read CSS, js and other files from node_modules\ortoni-report\dist.
If you share only the HTML file it won't work.

**Comment by changan1111** [comment]
Thanks for addressing. Any plans for that to implment in future?

**Comment by ortoniKC** [comment]
Sure, I'll try my best.

**Comment by KurnoolMaheshKumar** [comment]
I'm also kind of looking forward to sharing this report to clients post execution as i wanted to use ortoni as an alternative to allure-reports.

**Comment by ortoniKC** [comment]
Fixed in the latest version if V1.1.9. Please read the docs to use the feature.
Feel free create a new issue if any.

**Comment by rahulbendale03** [comment]
That's great news. Thanks @ortoniKC
