### ISSUE TITLE
console.log()

### ISSUE THREAD

**Issue by Arghajit47** [ortoniKC/ortoni-report#21]
In playwright default reporter, we have stdout option as well to see the console.log() statements. But In this reporter we don't have this option. kindly if you can configure that by default without creating an custom-reporter.ts file.

Also, kudos that you have achieved this much. Thanks in advance.

Attaching a few screenshots for your reference.

<img width="1440" alt="Screenshot 2024-08-22 at 11 59 14 PM" src="https://github.com/user-attachments/assets/b414018d-8ac6-4338-9e3e-502f22d3dcc7">

**Comment by ortoniKC** [comment]
I believe I have implemented this, anyways I'll take a look again.

**Comment by ortoniKC** [comment]
It is implemented,
Console logs visible on the reporter.

**Comment by ortoniKC** [comment]
I understand the issue very lately, yes the console logs are not visible, I should be fixed in the next release
