### ISSUE TITLE
[Query] Is it possible to bundle all other files too into the same result.html file ? 

### ISSUE THREAD

**Issue by shortcut2yp** [ortoniKC/ortoni-report#22]
<img width="412" alt="Screenshot 2024-09-15 at 9 20 38 AM" src="https://github.com/user-attachments/assets/68730b29-480e-4a59-803f-f065c960fb1b">

Use Case - We are saving the report generated in S3 bucket which is private. Now if we open .html file since the css is not accessible , the UI breaks.  Looking for something like extentReport where everything is merged into a single html file.

**Comment by ortoniKC** [comment]
If you upload the bundled folder doesn't it work?

**Comment by shortcut2yp** [comment]
above screenshot is from the files inside the bundle folder.  looks like this and if we check the html report , it points to css file present in the same folder , due to which it does't work. 
<img width="321" alt="Screenshot 2024-09-15 at 2 03 46 PM" src="https://github.com/user
<img width="436" alt="Screenshot 2024-09-15 at 2 05 38 PM" src="https://github.com/user-attachments/assets/0977db5c-b4ab-4d54-8190-32e45087a7d6">
-attachments/assets/cc19d06a-a016-4d71-a869-c790fc631508">
<img width="909" alt="Screenshot 2024-09-15 at 2 04 36 PM" src="https://github.com/user-attachments/assets/eccc0d2d-09c7-4f29-a499-fc352a738d12">

**Comment by ortoniKC** [comment]
Just for clarification, you uploaded the folder and still the css is not shown on the report right?

**Comment by shortcut2yp** [comment]
yup css doesn't show on the report because it is a separate file and since the bucket is private , one file is not able to access contents of the other files. Issue will not happen on a public S3 bucket. 

btw observed same behaviour locally too , in case after building ... you remove the css file from the folder , report UI will break. If it is possible to make css inline in HTML , will solve the issue.

**Comment by ortoniKC** [comment]
As the css file size is big, I am not able to do the inline css, I have to reduce the file size. 
I'll work on it. 
Thanks.

**Comment by ortoniKC** [comment]
It is fixed in V2.0.3,
Please reopen a ticket if you're facing any issue.

**Comment by ortoniKC** [comment]
Hi, is the css working properly now?

**Comment by shortcut2yp** [comment]
haan looks good to me. I saw the issue opened , not facing it.  To me steps section looks like this initially , but on clicking it does expands and steps are visible. May be a icon can be added to show it is clickable. 
<img width="1082" alt="Screenshot 2024-10-13 at 5 26 15 PM" src="https://github.com/user-attachments/assets/dcd959d7-0ad5-4952-85ad-80903347e7d9">

-
