### ISSUE TITLE
[Improvement] Screenshot Position

### ISSUE THREAD

**Issue by shortcut2yp** [ortoniKC/ortoni-report#3]
Screenshot is currently at same hierarchy of `Duration` , due to which it gets right aligned. In cases where log text length is long , screenshot goes further right and goes out of the screen.

Currently it looks like
![image](https://github.com/ortoniKC/ortoni-report/assets/32234622/7b639cc5-1e1d-4bf5-b0ec-21e004d1a408)

Is it designed to be like this ? or can we move screenshot element inside same Div as Duration
which will make it look like
![image](https://github.com/ortoniKC/ortoni-report/assets/32234622/c9f698ab-5e55-465d-8f23-da44853deadb)

**Comment by ortoniKC** [comment]
It is intentionally designed like this, as I want to bring the test steps in that gap.

**Comment by ortoniKC** [comment]
I can improve the log element to wrap so that it won't push other elements to overflow.

**Comment by ortoniKC** [comment]
Improved in the V1.1.0 pls check.

**Comment by shortcut2yp** [comment]
working ! Thanks 🙌
