### ISSUE TITLE
Unable to view trace in the pipeline 

### ISSUE THREAD

**Issue by abhia-ca** [ortoniKC/ortoni-report#34]
Hi!

I have uploaded the Ortoni report on s3 and I can view the report except the trace. My reports are being a VPN and I can access the normal playwright HTML report including the trace, images and video. 

When I try to open the trace from the Ortoni report, I get denied access. I have looked at the URL for the trace and compared it to the one on the default playwright HTML report and they are different. Ortoni mauses localhost while thether one has the actual s3 bucket URL.

HTML REPORT's TRACE URL: https://<S3 BUCKET>/<Test Name>/trace/index.html?trace=
https://<S3 BUCKET>/<Test Name>/data/<trace name>.zip

ORTONI Report's Trace URL: https://<S3 BUCKET>/ortoni-report/trace/index.html?trace=http://localhost:2004/ortoni-data/attachments/<UUID>/<trace name>.zip

Can you advise, how this can be fixed?

**Comment by ortoniKC** [comment]
Yes, it is fixed in the local version. 
I'll update the fix tomorrow.
