### ISSUE TITLE
Not all test results were visible and Test details are mismatched

### ISSUE THREAD

**Issue by Ronaldoacha** [ortoniKC/ortoni-report#4]
I tried OrtoniReport generator, not all test results were visible.
 
<img width="809" alt="upload" src="https://github.com/ortoniKC/ortoni-report/assets/79972612/3019947c-f100-4eca-ade5-bd3885dc3aed">

Total tests 18
5 passed
Number Failed 0 ( it returned 0 instead of 13). 

I will try the latest update/version 1.0.9 and keep feedback

**Comment by ortoniKC** [comment]
I understood the issue, if tests are failed it is taking status as failed, but when tests are timeout it is not considered as failed.
I will update the code.

**Comment by Ronaldoacha** [comment]
I have updated and tested V1.0.9, 
<img width="534" alt="upload2" src="https://github.com/ortoniKC/ortoni-report/assets/79972612/c7196d16-ecb3-4f70-970a-47fd68b5ca72">
Becoming more interesting but I think the number of test failed should be taken into consideration because I still get wrong details.

**Comment by Ronaldoacha** [comment]
> I understood the issue, if tests are failed it is taking status as failed, but when tests are timeout it is not considered as failed. I will update the code.

I will keep testing as you updates the changes

**Comment by ortoniKC** [comment]
Fixed in the V1.1.0 pls do check. Thanks.
