### ISSUE TITLE
Question_Is there any jenkins plugin setup for the same.

### ISSUE THREAD

**Issue by shashankkvs309668** [ortoniKC/ortoni-report#43]
Question_Is there any jenkins plugin setup for the same.

**Comment by shashankkvs309668** [comment]
Nope, the scenario im looking at is  when running in Jenkins it will be easy to get the reports like allure-report does. I actually di liked this ui representation of the reports.

**Comment by shashankkvs309668** [comment]
And facing one issue as of now, when having this report configured. console.log() statement is not printing in my terminal. The only way i can view is through your reports

**Comment by ortoniKC** [comment]
Update to the latest version console log is enabled by default.

**Comment by shashankkvs309668** [comment]
Console.log() is printing in the report. but im not able to see in the execution terminal
