### ISSUE TITLE
[BUG] Issue when running tests from VS code extension

### ISSUE THREAD

**Issue by fifernandez** [ortoniKC/ortoni-report#47]
Hi, I'm seeing something strange going on when running the tests inside vscode using the playwright extension.

The first time I try to run a test it goes fine, but the second time it just gets stuck, I can see on the playwright extension a timer but the test won't start. I have to click on the refresh tests button and run the test again for it to start, although the timer is still running... Another solution is to restart vscode...
I'm pretty sure it is because of this because when I remove the Ortoni report form from the reporter's list, the issue is gone. 
Any ideas?

**Comment by ortoniKC** [comment]
Hi, yes i observed the same, and I believe it is the extension and Ortoni Report test report completion sync issue, I will check from my.
As of now I have a work around, clicking on the refresh icon then you can run the tests again.
Pls refer to the video:

https://github.com/user-attachments/assets/6e36c426-514c-499c-8ccf-0996f357d11b

Mean while if you're using extension only to run test, yiu can checkout my vs code extension.
https://marketplace.visualstudio.com/items?itemName=ortoni.ortoni

**Comment by ortoniKC** [comment]
I am noticing the same with default report also, so it's not Ortoni Report problem.
