### ISSUE TITLE
Issue while installing the Report , are there any prereqs to be considered 

### ISSUE THREAD

**Issue by VasanthEzhilkumar** [ortoniKC/ortoni-report#48]
While installing the report im facing the issue during SQLlite intallation , i was able to install other extenstions but not the report any advice ?

silly packumentCache corgi:https://registry.npmjs.org/fast-glob set size:84869 disposed:false
541 info run sqlite3@5.1.7 install node_modules/sqlite3 prebuild-install -r napi || node-gyp rebuild
542 info run sqlite3@5.1.7 install { code: 1, signal: null }
543 verbose stack Error: command failed
543 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
543 verbose stack     at spawnWithShell (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
543 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
543 verbose stack     at runScriptPkg (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
543 verbose stack     at runScript (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
543 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
543 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
543 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
543 verbose stack     at new Promise (<anonymous>)
543 verbose stack     at callLimit (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
544 verbose pkgid sqlite3@5.1.7
545 error code 1
546 error path C:\Users\vezhil\Documents\WFM\node_modules\sqlite3
547 error command failed
548 error command C:\Windows\system32\cmd.exe /d /s /c prebuild-install -r napi || node-gyp rebuild
549 error prebuild-install info begin Prebuild-install version 7.1.2
549 error prebuild-install info looking for local prebuild @ prebuilds\sqlite3-v5.1.7-napi-v6-win32-x64.tar.gz
549 error prebuild-install info looking for cached prebuild @ C:\Users\vezhil\AppData\Local\npm-cache\_prebuilds\96dc75-sqlite3-v5.1.7-napi-v6-win32-x64.tar.gz
549 error prebuild-install http request GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.1.7/sqlite3-v5.1.7-napi-v6-win32-x64.tar.gz
549 error prebuild-install http request Proxy setup detected (Host: 165.225.196.22, Port: 10154, Authentication: No) Tunneling with httpsOverHttp
549 error prebuild-install warn install unable to get local issuer certificate
549 error gyp info it worked if it ends with ok
549 error gyp info using node-gyp@8.4.1
549 error gyp info using node@22.11.0 | win32 | x64
549 error (node:17112) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
549 error (Use `node --trace-deprecation ...` to show where the warning was created)
549 error gyp info find Python using Python version 3.13.0 found at "C:\Program Files\Python313\python.exe"
549 error gyp http GET https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz
549 error gyp WARN install got an error, rolling back install
549 error gyp ERR! configure error 
549 error gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz failed, reason: unable to get local issuer certificate
549 error gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\vezhil\Documents\WFM\node_modules\minipass-fetch\lib\index.js:110:14)
549 error gyp ERR! stack     at ClientRequest.emit (node:events:518:28)
549 error gyp ERR! stack     at emitErrorEvent (node:_http_client:103:11)
549 error gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:506:5)
549 error gyp ERR! stack     at TLSSocket.emit (node:events:518:28)
549 error gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:170:8)
549 error gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
549 error gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
549 error gyp ERR! System Windows_NT 10.0.14393
549 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vezhil\\Documents\\WFM\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
549 error gyp ERR! cwd C:\Users\vezhil\Documents\WFM\node_modules\sqlite3
549 error gyp ERR! node -v v22.11.0
549 error gyp ERR! node-gyp -v v8.4.1
549 error gyp ERR! not ok
550 silly unfinished npm timer reify 1732287882237
551 silly unfinished npm timer reify:build 1732287891400
552 silly unfinished npm timer build 1732287891401
553 silly unfinished npm timer build:deps 1732287891402
554 silly unfinished npm timer build:run:install 1732287891504
555 silly unfinished npm timer build:run:install:node_modules/sqlite3 1732287891504
556 verbose cwd C:\Users\vezhil\Documents\WFM
557 verbose os Windows_NT 10.0.14393
558 verbose node v22.11.0
559 verbose npm  v10.9.0
560 verbose exit 1
561 verbose code 1

**Comment by ortoniKC** [comment]
No prerequisite

**Comment by ortoniKC** [comment]
Hi, is it solved? 
Are you in a restricted network like an office vpn?

**Comment by VasanthEzhilkumar** [comment]
Hi Koushik ,

The issue is not resolved yet and im behind corporte proxy , i was able to install other extensions and report with corporate proxy

**Comment by ortoniKC** [comment]
Ok, could you pls check with version 2.0.6?
