### ISSUE TITLE
[Feature] Hierarchy of specs with project as highest level

### ISSUE THREAD

**Issue by kasikcz** [ortoniKC/ortoni-report#7]
I have like 7 projects most of the time and it would be less clicking
![image](https://github.com/ortoniKC/ortoni-report/assets/16073211/2123690f-c5c9-4b65-8e56-8bab34e4c2b1)

**Comment by ortoniKC** [comment]
Hello, 
Do you think this will help?
Selection based on the project name will show the relevant details.

![image](https://github.com/ortoniKC/ortoni-report/assets/58769833/e55d6893-25bd-4348-930b-ff8336058269)

**Comment by kasikcz** [comment]
Yes this might work as well

**Comment by ortoniKC** [comment]
It is easy to change the project location to first, but it might not be very useful to others. 
As the existing hierarchy order is relevant to most of the users. So keeping that in mind, I have implemented the filter selection. After the release you can try and let me know.

**Comment by ortoniKC** [comment]
It is fixed in the latest version of 1.1.5 https://www.npmjs.com/package/ortoni-report
